# See config.example.yml for documentation.
object: orig/GAFE01/sys/main.dol
hash: 2ae8f56e7791d37e165bd5900921f2269f9515bf
name: static
symbols: config/GAFE01/symbols.txt
splits: config/GAFE01/splits.txt
#map: orig/GAFE01/files/static.map
common_start: 0x8020D78C
mw_comment_version: 10
write_asm: false
symbols_known: true
fill_gaps: false

force_active: ["_savegpr_14", "_restgpr_14"] # Needed to fix references to __save_gpr/__restore_gpr

extract:
#dvderr.c
- symbol: ctl_att_w1_tex
  header: assets/ctl_att_w1_tex.inc
  
- symbol: ctl_att_w2_tex
  header: assets/ctl_att_w2_tex.inc
  
- symbol: ctl_att_w3_tex
  header: assets/ctl_att_w3_tex.inc
  
- symbol: ctl_att_w4_tex
  header: assets/ctl_att_w4_tex.inc
  
- symbol: ctl_att_w5_tex
  header: assets/ctl_att_w5_tex.inc
  
- symbol: ctl_att_w6_tex
  header: assets/ctl_att_w6_tex.inc

- symbol: dvd_keikoku_moji1_1_tex
  header: assets/dvd_keikoku_moji1_1_tex.inc
  
- symbol: dvd_keikoku_moji1_2_tex
  header: assets/dvd_keikoku_moji1_2_tex.inc
  
- symbol: dvd_keikoku_moji1_3_tex
  header: assets/dvd_keikoku_moji1_3_tex.inc
  
- symbol: dvd_keikoku_moji1_4_tex
  header: assets/dvd_keikoku_moji1_4_tex.inc
  
- symbol: dvd_keikoku_moji2_tex
  header: assets/dvd_keikoku_moji2_tex.inc
  
- symbol: dvd_keikoku_moji2_2_tex
  header: assets/dvd_keikoku_moji2_2_tex.inc
  
- symbol: dvd_keikoku_moji2_3_tex
  header: assets/dvd_keikoku_moji2_3_tex.inc
  
- symbol: dvd_keikoku_moji3_1_tex
  header: assets/dvd_keikoku_moji3_1_tex.inc
  
- symbol: dvd_keikoku_moji3_2_tex
  header: assets/dvd_keikoku_moji3_2_tex.inc
  
- symbol: dvd_keikoku_moji3_3_tex
  header: assets/dvd_keikoku_moji3_3_tex.inc
  
- symbol: dvd_keikoku_moji4_tex
  header: assets/dvd_keikoku_moji4_tex.inc
  
- symbol: dvd_keikoku_moji5_tex
  header: assets/dvd_keikoku_moji5_tex.inc

- symbol: dvd_keikoku_moji6_2_tex
  header: assets/dvd_keikoku_moji6_2_tex.inc

- symbol: dvd_keikoku_moji6_3_tex
  header: assets/dvd_keikoku_moji6_3_tex.inc

- symbol: dvd_keikoku_moji6_tex
  header: assets/dvd_keikoku_moji6_tex.inc

- symbol: dvd_keikoku_moji6_1_tex
  header: assets/dvd_keikoku_moji6_1_tex.inc

- symbol: dvd_keikoku_moji6_new1_tex
  header: assets/dvd_keikoku_moji6_new1_tex.inc

- symbol: dvd_keikoku_moji6_new2_tex
  header: assets/dvd_keikoku_moji6_new2_tex.inc

- symbol: dvd_keikoku_moji7_tex
  header: assets/dvd_keikoku_moji7_tex.inc

- symbol: dvd_keikoku_moji8_tex
  header: assets/dvd_keikoku_moji8_tex.inc

- symbol: dvd_keikoku_moji10_tex
  header: assets/dvd_keikoku_moji10_tex.inc

- symbol: dvd_keikoku_moji11_tex
  header: assets/dvd_keikoku_moji11_tex.inc

- symbol: dvd_keikoku_moji12_tex
  header: assets/dvd_keikoku_moji12_tex.inc

- symbol: dvd_keikoku_moji9_tex
  header: assets/dvd_keikoku_moji9_tex.inc

- symbol: dvd_keikoku1_v
  binary: assets/dvd_keikoku1_v.bin
  type: vtx

- symbol: dvd_keikoku2_v
  binary: assets/dvd_keikoku2_v.bin
  type: vtx

- symbol: dvd_keikoku3_v
  binary: assets/dvd_keikoku3_v.bin
  type: vtx

- symbol: dvd_keikoku4_v
  binary: assets/dvd_keikoku4_v.bin
  type: vtx

- symbol: dvd_keikoku5_v
  binary: assets/dvd_keikoku5_v.bin
  type: vtx

modules:
- object: orig/GAFE01/files/foresta.rel
  hash: c59d278ad8542bb05d6cbb632f60a0db05bef203
  symbols: config/GAFE01/foresta/symbols.txt
  splits: config/GAFE01/foresta/splits.txt
  #map: orig/GAFE01/files/foresta.map
  extract:
  #ac_boat_demo
  - symbol: aBTD_island_prg
    header: assets/aBTD_island_prg.inc

  - symbol: aBTD_island_ldr
    header: assets/aBTD_island_ldr.inc

  #ac_mbg
  - symbol: mbg_v
    binary: assets/mbg_v.bin
    type: vtx

  #ac_koinobori
  - symbol: aKOI_obj_e_koinobori_a_pal
    binary: assets/aKOI_obj_e_koinobori_a_pal.bin
    type: pal16

  - symbol: obj_e_koinobori_b_pal
    binary: assets/obj_e_koinobori_b_pal.bin
    type: pal16

  #ac_lotus
  - symbol: aLOT_obj_01_lotus_pal
    binary: assets/aLOT_obj_01_lotus_pal.bin
    type: pal16

  - symbol: obj_02_lotus_pal
    binary: assets/obj_02_lotus_pal.bin
    type: pal16

  - symbol: obj_03_lotus_pal
    binary: assets/obj_03_lotus_pal.bin
    type: pal16

  - symbol: obj_04_lotus_pal
    binary: assets/obj_04_lotus_pal.bin
    type: pal16

  - symbol: obj_05_lotus_pal
    binary: assets/obj_05_lotus_pal.bin
    type: pal16

  - symbol: obj_06_lotus_pal
    binary: assets/obj_06_lotus_pal.bin
    type: pal16

  - symbol: obj_07_lotus_pal
    binary: assets/obj_07_lotus_pal.bin
    type: pal16

  - symbol: obj_08_lotus_pal
    binary: assets/obj_08_lotus_pal.bin
    type: pal16

  - symbol: obj_09_lotus_pal
    binary: assets/obj_09_lotus_pal.bin
    type: pal16
    
  #ef_coin
  - symbol: ef_coin_gold_pal
    binary: assets/ef_coin_gold_pal.bin
    type: pal16

  - symbol: ef_coin_silver_pal
    binary: assets/ef_coin_silver_pal.bin
    type: pal16

  #f_furniture
  - symbol: int_nog_kamakura_off_pal
    binary: assets/int_nog_kamakura_off_pal.bin
    type: pal16

  - symbol: int_nog_kamakura_on_pal
    binary: assets/int_nog_kamakura_on_pal.bin
    type: pal16

  - symbol: int_nog_kouban_on_pal
    binary: assets/int_nog_kouban_on_pal.bin
    type: pal16

  - symbol: int_nog_kouban_off_pal
    binary: assets/int_nog_kouban_off_pal.bin
    type: pal16

  - symbol: int_nog_museum_off_pal
    binary: assets/int_nog_museum_off_pal.bin
    type: pal16

  - symbol: int_nog_museum_on_pal
    binary: assets/int_nog_museum_on_pal.bin
    type: pal16

  - symbol: int_nog_station1_a_pal
    binary: assets/int_nog_station1_a_pal.bin
    type: pal16

  - symbol: int_nog_station1_b_pal
    binary: assets/int_nog_station1_b_pal.bin
    type: pal16

  - symbol: int_nog_station1_c_pal
    binary: assets/int_nog_station1_c_pal.bin
    type: pal16

  - symbol: int_nog_station1_d_pal
    binary: assets/int_nog_station1_d_pal.bin
    type: pal16

  - symbol: int_nog_station1_e_pal
    binary: assets/int_nog_station1_e_pal.bin
    type: pal16

  - symbol: int_nog_station2_a_pal
    binary: assets/int_nog_station2_a_pal.bin
    type: pal16

  - symbol: int_nog_station2_b_pal
    binary: assets/int_nog_station2_b_pal.bin
    type: pal16

  - symbol: int_nog_station2_c_pal
    binary: assets/int_nog_station2_c_pal.bin
    type: pal16

  - symbol: int_nog_station2_d_pal
    binary: assets/int_nog_station2_d_pal.bin
    type: pal16

  - symbol: int_nog_station2_e_pal
    binary: assets/int_nog_station2_e_pal.bin
    type: pal16

  - symbol: int_nog_station3_a_pal
    binary: assets/int_nog_station3_a_pal.bin
    type: pal16

  - symbol: int_nog_station3_b_pal
    binary: assets/int_nog_station3_b_pal.bin
    type: pal16

  - symbol: int_nog_station3_c_pal
    binary: assets/int_nog_station3_c_pal.bin
    type: pal16

  - symbol: int_nog_station3_d_pal
    binary: assets/int_nog_station3_d_pal.bin
    type: pal16

  - symbol: int_nog_station3_e_pal
    binary: assets/int_nog_station3_e_pal.bin
    type: pal16

  - symbol: int_nog_shop1_off_pal
    binary: assets/int_nog_shop1_off_pal.bin
    type: pal16

  - symbol: int_nog_shop1_on_pal
    binary: assets/int_nog_shop1_on_pal.bin
    type: pal16

  - symbol: int_nog_uranai_off_pal
    binary: assets/int_nog_uranai_off_pal.bin
    type: pal16

  - symbol: int_nog_uranai_on_pal
    binary: assets/int_nog_uranai_on_pal.bin
    type: pal16

  - symbol: int_nog_yamishop_off_pal
    binary: assets/int_nog_yamishop_off_pal.bin
    type: pal16

  - symbol: int_nog_yamishop_on_pal
    binary: assets/int_nog_yamishop_on_pal.bin
    type: pal16

  - symbol: int_nog_yubin_on_pal
    binary: assets/int_nog_yubin_on_pal.bin
    type: pal16

  - symbol: int_nog_yubin_off_pal
    binary: assets/int_nog_yubin_off_pal.bin
    type: pal16

  - symbol: int_tak_tailor_on_pal
    binary: assets/int_tak_tailor_on_pal.bin
    type: pal16

  - symbol: int_tak_tailor_off_pal
    binary: assets/int_tak_tailor_off_pal.bin
    type: pal16

  - symbol: radio_pal$6603
    binary: assets/radio_pal.bin
    type: pal16

  - symbol: int_yaz_fish_trophy_pal
    binary: assets/int_yaz_fish_trophy_pal.bin
    type: pal16

  - symbol: int_tak_tent_on_pal
    binary: assets/int_tak_tent_on_pal.bin
    type: pal16

  - symbol: int_tak_tent_off_pal
    binary: assets/int_tak_tent_off_pal.bin
    type: pal16

  - symbol: int_yaz_fish_trophy2_pal
    binary: assets/int_yaz_fish_trophy2_pal.bin
    type: pal16

  - symbol: int_nog_flower_a_pal
    binary: assets/int_nog_flower_a_pal.bin
    type: pal16

  - symbol: int_nog_flower_b_pal
    binary: assets/int_nog_flower_b_pal.bin
    type: pal16

  - symbol: int_nog_flower_c_pal
    binary: assets/int_nog_flower_c_pal.bin
    type: pal16

  #m_choice
  - symbol: con_waku_swaku3_tex
    header: assets/con_waku_swaku3_tex.inc

  - symbol: con_sentaku2_v
    binary: assets/con_sentaku2_v.bin
    type: vtx

  #m_fbdemo_wipe1
  - symbol: wipe1_v
    binary: assets/wipe1_v.bin
    type: vtx

  - symbol: g_wipe1_txt
    header: assets/g_wipe1_txt.inc

  #m_msg
  - symbol: con_kaiwa2_w1_tex
    header: assets/msg/con_kaiwa2_w1_tex.inc

  - symbol: con_kaiwa2_w2_tex
    header: assets/msg/con_kaiwa2_w2_tex.inc

  - symbol: con_kaiwa2_w3_tex
    header: assets/msg/con_kaiwa2_w3_tex.inc

  - symbol: con_kaiwa2_v
    binary: assets/msg/con_kaiwa2_v.bin
    type: vtx

  - symbol: con_namefuti_TXT
    header: assets/msg/con_namefuti_TXT.inc

  - symbol: con_kaiwaname_v
    binary: assets/msg/con_kaiwaname_v.bin
    type: vtx
