object: orig/GAFE01/sys/main.dol
hash: 2ae8f56e7791d37e165bd5900921f2269f9515bf
name: static
symbols: config/GAFE01/symbols.txt
splits: config/GAFE01/splits.txt
#map: orig/GAFE01/files/static.map
common_start: 0x8020D78C
mw_comment_version: 10
#write_asm: false
symbols_known: true
fill_gaps: false

extract:
#bootdata/gam_win1
- symbol: gam_win_moji1_tex
  header: assets/bootdata/win1/gam_win_moji1_tex.inc

- symbol: gam_win_moji2_tex
  header: assets/bootdata/win1/gam_win_moji2_tex.inc

- symbol: yes
  header: assets/bootdata/win1/yes.inc

- symbol: no
  header: assets/bootdata/win1/no.inc

- symbol: att_win_waku1_tex!.data:0x800b9a40
  header: assets/bootdata/win1/att_win_waku1_tex.inc

- symbol: att_win_waku2_tex!.data:0x800b9e40
  header: assets/bootdata/win1/att_win_waku2_tex.inc

- symbol: att_win_waku3_tex!.data:0x800ba240
  header: assets/bootdata/win1/att_win_waku3_tex.inc

- symbol: att_win_waku4_tex!.data:0x800ba640
  header: assets/bootdata/win1/att_win_waku4_tex.inc

- symbol: att_win_waku5_tex!.data:0x800baa40
  header: assets/bootdata/win1/att_win_waku5_tex.inc

- symbol: att_win_waku6_tex!.data:0x800bae40
  header: assets/bootdata/win1/att_win_waku6_tex.inc

- symbol: gam_win1_v
  binary: assets/bootdata/win1/gam_win1_v.bin
  type: vtx

#bootdata/gam_win2
- symbol: gam_win_moji3_tex!.data:0x800bb500
  header: assets/bootdata/win2/gam_win_moji3_tex.inc

- symbol: gam_win_moji4_tex!.data:0x800bba00
  header: assets/bootdata/win2/gam_win_moji4_tex.inc

- symbol: att_win_waku1_tex!.data:0x800bbf00
  header: assets/bootdata/win2/att_win_waku1_tex.inc

- symbol: att_win_waku2_tex!.data:0x800bc300
  header: assets/bootdata/win2/att_win_waku2_tex.inc

- symbol: att_win_waku3_tex!.data:0x800bc700
  header: assets/bootdata/win2/att_win_waku3_tex.inc

- symbol: att_win_waku4_tex!.data:0x800bcb00
  header: assets/bootdata/win2/att_win_waku4_tex.inc

- symbol: att_win_waku5_tex!.data:0x800bcf00
  header: assets/bootdata/win2/att_win_waku5_tex.inc

- symbol: att_win_waku6_tex!.data:0x800bd300
  header: assets/bootdata/win2/att_win_waku6_tex.inc

- symbol: gam_win2_v
  binary: assets/bootdata/win2/gam_win2_v.bin
  type: vtx

#bootdata/gam_win3
- symbol: gam_win_moji3_tex!.data:0x800bd820
  header: assets/bootdata/win3/gam_win_moji3_tex.inc

- symbol: gam_win_moji5_tex!.data:0x800bdd20
  header: assets/bootdata/win3/gam_win_moji5_tex.inc

- symbol: gam_win3_v
  binary: assets/bootdata/win3/gam_win3_v.bin
  type: vtx

#bootdata/logo_nin
- symbol: nintendo_376x104
  header: assets/bootdata/nintendo_376x104.inc

- symbol: logo_nin_v
  binary: assets/bootdata/logo_nin_v.bin
  type: vtx

#JUtility
- symbol: JUTResFONT_Ascfont_fix12
  binary: JSystem/JUtility/FontData/Ascfont_fix12.bfn

modules:
- object: orig/GAFE01/files/foresta.rel
  hash: c59d278ad8542bb05d6cbb632f60a0db05bef203
  symbols: config/GAFE01/foresta/symbols.txt
  splits: config/GAFE01/foresta/splits.txt
  #map: orig/GAFE01/files/foresta.map
  extract:
  #ac_boat_demo
  - symbol: aBTD_island_prg
    header: assets/aBTD_island_prg.inc

  - symbol: aBTD_island_ldr
    header: assets/aBTD_island_ldr.inc

  #ac_mbg
  - symbol: mbg_v
    binary: assets/mbg_v.bin
    type: vtx

  #ac_koinobori
  - symbol: aKOI_obj_e_koinobori_a_pal
    binary: assets/aKOI_obj_e_koinobori_a_pal.bin
    type: pal16

  - symbol: obj_e_koinobori_b_pal
    binary: assets/obj_e_koinobori_b_pal.bin
    type: pal16

  #ac_lotus
  - symbol: aLOT_obj_01_lotus_pal
    binary: assets/aLOT_obj_01_lotus_pal.bin
    type: pal16

  - symbol: obj_02_lotus_pal
    binary: assets/obj_02_lotus_pal.bin
    type: pal16

  - symbol: obj_03_lotus_pal
    binary: assets/obj_03_lotus_pal.bin
    type: pal16

  - symbol: obj_04_lotus_pal
    binary: assets/obj_04_lotus_pal.bin
    type: pal16

  - symbol: obj_05_lotus_pal
    binary: assets/obj_05_lotus_pal.bin
    type: pal16

  - symbol: obj_06_lotus_pal
    binary: assets/obj_06_lotus_pal.bin
    type: pal16

  - symbol: obj_07_lotus_pal
    binary: assets/obj_07_lotus_pal.bin
    type: pal16

  - symbol: obj_08_lotus_pal
    binary: assets/obj_08_lotus_pal.bin
    type: pal16

  - symbol: obj_09_lotus_pal
    binary: assets/obj_09_lotus_pal.bin
    type: pal16
    
  #ef_coin
  - symbol: ef_coin_gold_pal
    binary: assets/ef_coin_gold_pal.bin
    type: pal16

  - symbol: ef_coin_silver_pal
    binary: assets/ef_coin_silver_pal.bin
    type: pal16

  #f_furniture
  - symbol: int_nog_kamakura_off_pal
    binary: assets/int_nog_kamakura_off_pal.bin
    type: pal16

  - symbol: int_nog_kamakura_on_pal
    binary: assets/int_nog_kamakura_on_pal.bin
    type: pal16

  - symbol: int_nog_kouban_on_pal
    binary: assets/int_nog_kouban_on_pal.bin
    type: pal16

  - symbol: int_nog_kouban_off_pal
    binary: assets/int_nog_kouban_off_pal.bin
    type: pal16

  - symbol: int_nog_museum_off_pal
    binary: assets/int_nog_museum_off_pal.bin
    type: pal16

  - symbol: int_nog_museum_on_pal
    binary: assets/int_nog_museum_on_pal.bin
    type: pal16

  - symbol: int_nog_station1_a_pal
    binary: assets/int_nog_station1_a_pal.bin
    type: pal16

  - symbol: int_nog_station1_b_pal
    binary: assets/int_nog_station1_b_pal.bin
    type: pal16

  - symbol: int_nog_station1_c_pal
    binary: assets/int_nog_station1_c_pal.bin
    type: pal16

  - symbol: int_nog_station1_d_pal
    binary: assets/int_nog_station1_d_pal.bin
    type: pal16

  - symbol: int_nog_station1_e_pal
    binary: assets/int_nog_station1_e_pal.bin
    type: pal16

  - symbol: int_nog_station2_a_pal
    binary: assets/int_nog_station2_a_pal.bin
    type: pal16

  - symbol: int_nog_station2_b_pal
    binary: assets/int_nog_station2_b_pal.bin
    type: pal16

  - symbol: int_nog_station2_c_pal
    binary: assets/int_nog_station2_c_pal.bin
    type: pal16

  - symbol: int_nog_station2_d_pal
    binary: assets/int_nog_station2_d_pal.bin
    type: pal16

  - symbol: int_nog_station2_e_pal
    binary: assets/int_nog_station2_e_pal.bin
    type: pal16

  - symbol: int_nog_station3_a_pal
    binary: assets/int_nog_station3_a_pal.bin
    type: pal16

  - symbol: int_nog_station3_b_pal
    binary: assets/int_nog_station3_b_pal.bin
    type: pal16

  - symbol: int_nog_station3_c_pal
    binary: assets/int_nog_station3_c_pal.bin
    type: pal16

  - symbol: int_nog_station3_d_pal
    binary: assets/int_nog_station3_d_pal.bin
    type: pal16

  - symbol: int_nog_station3_e_pal
    binary: assets/int_nog_station3_e_pal.bin
    type: pal16

  - symbol: int_nog_shop1_off_pal
    binary: assets/int_nog_shop1_off_pal.bin
    type: pal16

  - symbol: int_nog_shop1_on_pal
    binary: assets/int_nog_shop1_on_pal.bin
    type: pal16

  - symbol: int_nog_uranai_off_pal
    binary: assets/int_nog_uranai_off_pal.bin
    type: pal16

  - symbol: int_nog_uranai_on_pal
    binary: assets/int_nog_uranai_on_pal.bin
    type: pal16

  - symbol: int_nog_yamishop_off_pal
    binary: assets/int_nog_yamishop_off_pal.bin
    type: pal16

  - symbol: int_nog_yamishop_on_pal
    binary: assets/int_nog_yamishop_on_pal.bin
    type: pal16

  - symbol: int_nog_yubin_on_pal
    binary: assets/int_nog_yubin_on_pal.bin
    type: pal16

  - symbol: int_nog_yubin_off_pal
    binary: assets/int_nog_yubin_off_pal.bin
    type: pal16

  - symbol: int_tak_tailor_on_pal
    binary: assets/int_tak_tailor_on_pal.bin
    type: pal16

  - symbol: int_tak_tailor_off_pal
    binary: assets/int_tak_tailor_off_pal.bin
    type: pal16

  - symbol: radio_pal$6603
    binary: assets/radio_pal.bin
    type: pal16

  - symbol: int_yaz_fish_trophy_pal
    binary: assets/int_yaz_fish_trophy_pal.bin
    type: pal16

  - symbol: int_tak_tent_on_pal
    binary: assets/int_tak_tent_on_pal.bin
    type: pal16

  - symbol: int_tak_tent_off_pal
    binary: assets/int_tak_tent_off_pal.bin
    type: pal16

  - symbol: int_yaz_fish_trophy2_pal
    binary: assets/int_yaz_fish_trophy2_pal.bin
    type: pal16

  - symbol: int_nog_flower_a_pal
    binary: assets/int_nog_flower_a_pal.bin
    type: pal16

  - symbol: int_nog_flower_b_pal
    binary: assets/int_nog_flower_b_pal.bin
    type: pal16

  - symbol: int_nog_flower_c_pal
    binary: assets/int_nog_flower_c_pal.bin
    type: pal16

  #m_choice
  - symbol: con_waku_swaku3_tex
    header: assets/con_waku_swaku3_tex.inc

  - symbol: con_sentaku2_v
    binary: assets/con_sentaku2_v.bin
    type: vtx

  #m_fbdemo_wipe1
  - symbol: wipe1_v
    binary: assets/wipe1_v.bin
    type: vtx

  - symbol: g_wipe1_txt
    header: assets/g_wipe1_txt.inc

  #m_msg
  - symbol: con_kaiwa2_w1_tex
    header: assets/msg/con_kaiwa2_w1_tex.inc

  - symbol: con_kaiwa2_w2_tex
    header: assets/msg/con_kaiwa2_w2_tex.inc

  - symbol: con_kaiwa2_w3_tex
    header: assets/msg/con_kaiwa2_w3_tex.inc

  - symbol: con_kaiwa2_v
    binary: assets/msg/con_kaiwa2_v.bin
    type: vtx

  - symbol: con_namefuti_TXT
    header: assets/msg/con_namefuti_TXT.inc

  - symbol: con_kaiwaname_v
    binary: assets/msg/con_kaiwaname_v.bin
    type: vtx
